name: Build Flutter Android APK and Deploy

on:
  push:
    branches: ["flutterflow"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK (release)
      run: flutter build apk --release

    - name: Deploy APK to Android repository
      run: |
        git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/sergiogar6/DespliegueMovil.git android-repo
        rm -rf android-repo/*
        cp build/app/outputs/flutter-apk/app-release.apk android-repo/
        cd android-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy Android APK"
        git push
